apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: election
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2 # Start with 2 replicas to ensure high availability
  maxReplicas: 4 # Allow scaling up to 4 replicas during peak load
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Scale up when average CPU usage exceeds 70%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15 # Allow doubling the number of pods every 15 seconds if needed
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Max # Choose the more aggressive policy when scaling up
    scaleDown:
      stabilizationWindowSeconds: 300 # Wait for 5 minutes before scaling down to avoid flapping
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      selectPolicy: Min
