apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: election
  labels:
    app: backend
    tier: application
spec:
  type: ClusterIP # Internal service
  selector:
    app: backend
  ports:
  - port: 8000 # Expose port 8000 for the backend application
    targetPort: 8000
    protocol: TCP
    name: http
