apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: election
  labels:
    app: frontend
    tier: presentation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: presentation
    spec:
      containers:
      - name: frontend
        image: sa-election-frontend:v2 # Use the new image tag for the updated frontend
        imagePullPolicy: IfNotPresent  # Ensure the new image is pulled only if it's not already present on the node
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1 # The app is considered ready after 1 successful check
          failureThreshold: 3 # If the app fails to become ready after 3 attempts, it will be marked as Unready
